# Form implementation generated from reading ui file '.\calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.firstNumber = QtWidgets.QLabel(parent=Form)
        self.firstNumber.setObjectName("firstNumber")
        self.horizontalLayout.addWidget(self.firstNumber)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.firstLine = QtWidgets.QLineEdit(parent=Form)
        self.firstLine.setObjectName("firstLine")
        self.horizontalLayout.addWidget(self.firstLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.secondNumber = QtWidgets.QLabel(parent=Form)
        self.secondNumber.setObjectName("secondNumber")
        self.horizontalLayout_2.addWidget(self.secondNumber)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.SecondLine = QtWidgets.QLineEdit(parent=Form)
        self.SecondLine.setObjectName("SecondLine")
        self.horizontalLayout_2.addWidget(self.SecondLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setObjectName("addButton")
        self.addButton.clicked.connect(self.add)
        self.horizontalLayout_3.addWidget(self.addButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.minusButton = QtWidgets.QPushButton(parent=Form)
        self.minusButton.setObjectName("minusButton")
        self.minusButton.clicked.connect(self.minus)
        self.horizontalLayout_3.addWidget(self.minusButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.multiplicationButton = QtWidgets.QPushButton(parent=Form)
        self.multiplicationButton.setObjectName("multiplicationButton")
        self.multiplicationButton.clicked.connect(self.multiply)
        self.horizontalLayout_3.addWidget(self.multiplicationButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.divideButton = QtWidgets.QPushButton(parent=Form)
        self.divideButton.setObjectName("divideButton")
        self.divideButton.clicked.connect(self.divide)
        self.horizontalLayout_3.addWidget(self.divideButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.resultLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.horizontalLayout_4.addWidget(self.resultLabel)
        self.Result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Result.setFont(font)
        self.Result.setObjectName("Result")
        self.horizontalLayout_4.addWidget(self.Result)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self):
        fnum = int(self.firstLine.text())
        snum = int(self.SecondLine.text())
        result = fnum + snum
        self.Result.setText(str(result))

    def minus(self):
        fnum = int(self.firstLine.text())
        snum = int(self.SecondLine.text())
        result = fnum - snum
        self.Result.setText(str(result))

    def multiply(self):
        fnum = int(self.firstLine.text())
        snum = int(self.SecondLine.text())
        result = fnum * snum
        self.Result.setText(str(result))

    def divide(self):
        fnum = int(self.firstLine.text())
        snum = int(self.SecondLine.text())
        result = fnum / snum
        self.Result.setText(str(result))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.firstNumber.setText(_translate("Form", "First Number : "))
        self.firstLine.setPlaceholderText(_translate("Form", "Please Enter First Number"))
        self.secondNumber.setText(_translate("Form", "Second Number : "))
        self.SecondLine.setPlaceholderText(_translate("Form", "Please Enter Second Number"))
        self.addButton.setText(_translate("Form", "+"))
        self.minusButton.setText(_translate("Form", "-"))
        self.multiplicationButton.setText(_translate("Form", "*"))
        self.divideButton.setText(_translate("Form", "/"))
        self.resultLabel.setText(_translate("Form", "result"))
        self.Result.setText(_translate("Form", "result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
