# Form implementation generated from reading ui file '.\flight.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6.QtWidgets import QDialog

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 150)
        Dialog.setStyleSheet("QDialog {\n"
"background-color:yellow\n"
"}\n"
"\n"
"QLabel {\n"
"color:green\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_first = QtWidgets.QRadioButton(parent=Dialog)
        self.rb_first.setObjectName("rb_first")
        self.rb_first.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.rb_first)
        self.rb_business = QtWidgets.QRadioButton(parent=Dialog)
        self.rb_business.setObjectName("rb_business")
        self.rb_business.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.rb_business)
        self.rb_eco = QtWidgets.QRadioButton(parent=Dialog)
        self.rb_eco.setObjectName("rb_eco")
        self.rb_eco.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.rb_eco)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("")
        self.verticalLayout_2.addWidget(self.label_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.label_2.setText("You Have PicK : {}".format(radio_btn.text()))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select Flight Type "))
        self.rb_first.setText(_translate("Dialog", "First Class $150"))
        self.rb_business.setText(_translate("Dialog", "Business Class $120"))
        self.rb_eco.setText(_translate("Dialog", "Economy Class $90"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
